# Generated by Django 4.1 on 2022-08-22 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentAPIService',
            new_name='StudentAPI',
        ),
    ]
